// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTrungTamTinHoc_NgoaiNgu.Data;

#nullable disable

namespace QuanLyTrungTamTinHoc_NgoaiNgu.Migrations
{
    [DbContext(typeof(QLTTDbContext))]
    partial class QLTTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("MaCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailGV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhGV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaGV")
                        .IsUnique();

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocPhi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int?>("LopHocID")
                        .HasColumnType("int");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDongHocPhi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("LopHocID");

                    b.ToTable("HocPhi");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LopHocID");

                    b.HasIndex("MaHV")
                        .IsUnique();

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KetQua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("DiemSo")
                        .HasColumnType("float");

                    b.Property<int>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDiemID")
                        .HasColumnType("int");

                    b.Property<int?>("LopHocID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("LoaiDiemID");

                    b.HasIndex("LopHocID");

                    b.ToTable("KetQua");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaKH")
                        .IsUnique();

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LichHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BuoiSo")
                        .HasColumnType("int");

                    b.Property<int>("CaHocID")
                        .HasColumnType("int");

                    b.Property<int>("GiangVienID")
                        .HasColumnType("int");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongHocID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaHocID");

                    b.HasIndex("GiangVienID");

                    b.HasIndex("LopHocID");

                    b.HasIndex("PhongHocID");

                    b.HasIndex("NgayHoc", "CaHocID", "GiangVienID")
                        .IsUnique();

                    b.HasIndex("NgayHoc", "CaHocID", "PhongHocID")
                        .IsUnique();

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("HeSo")
                        .HasColumnType("float");

                    b.Property<string>("MaLD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiDiem");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("KhoaHocID");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BoPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhienDangNhap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDangXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("PhienDangNhap");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.Quyen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuyenID")
                        .HasColumnType("int");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("QuyenID");

                    b.HasIndex("TenDN")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocPhi", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", "HocVien")
                        .WithMany("HocPhis")
                        .HasForeignKey("HocVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", null)
                        .WithMany("HocPhis")
                        .HasForeignKey("LopHocID");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", "LopHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KetQua", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", "HocVien")
                        .WithMany("KetQuas")
                        .HasForeignKey("HocVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", "LoaiDiem")
                        .WithMany("KetQuas")
                        .HasForeignKey("LoaiDiemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", null)
                        .WithMany("KetQuas")
                        .HasForeignKey("LopHocID");

                    b.Navigation("HocVien");

                    b.Navigation("LoaiDiem");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LichHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", "CaHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("CaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", "GiangVien")
                        .WithMany("LichHocs")
                        .HasForeignKey("GiangVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", "LopHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", "PhongHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("PhongHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaHoc");

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.NhanVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhienDangNhap", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("PhienDangNhaps")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.Quyen", "Quyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("QuyenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", b =>
                {
                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.Navigation("HocPhis");

                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.Navigation("HocPhis");

                    b.Navigation("HocViens");

                    b.Navigation("KetQuas");

                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", b =>
                {
                    b.Navigation("LichHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.Quyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", b =>
                {
                    b.Navigation("PhienDangNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
